### ISSUE TITLE
Not able to 'undeploy'  dmrpp-generator

### ISSUE THREAD

**Issue by lbaatz** [ghrcdaac/dmrpp-generator#10]
I deployed DMR++ as documented for some prototyping work. It deployed without issue. After my work, I then tried to remove the module "dmrpp-generator" block from our main.tf. Upon redeploying Cumulus I got: 

Error: Provider configuration not present. To work with module.dmrpp-generator.module.dmrpp_service.module.dmrpp_service.aws_ecs_task_definition.default its original provider configuration at module.dmrpp-generator.provider.aws is required, but it has been removed. This occurs when a provider configuration is removed while objects created by that provider still exist in the state. Re-add the provider configuration to destroy module.dmrpp-generator.module.dmrpp_service.module.dmrpp_service.aws_ecs_task_definition.default, after which you can remove the provider configuration again.

To 'undeploy' dmrpp-generator, I had to modify it's main.tf to remove this block:
provider "aws" {
  region  = var.region
  profile = var.aws_profile
}
and redeploy. I was then able to remove the module "dmrpp-generator" block from our main.tf, and redeploy successfully.

This was helpful in resolving the issue: https://www.terraform.io/docs/modules/providers.html

**Comment by amarouane-ABDELHAK** [comment]
Resolved in the release v1.1.0
