### ISSUE TITLE
Add optional flags to DMRPP generator from cumulus workflow

### ISSUE THREAD

**Issue by mgangl** [ghrcdaac/dmrpp-generator#11]
PO.DAAC has a need to use certain flags with some data products when generating data flags.

for example, our ECCO data files need to use the -M option (missing)

```
 -M: Create and merge missing CF coordinate domain variables into the dmrpp. If there are
     missing variables, a sidecar file named <input_file_name>.missing will be created
     in the same directory location as the input_data_file.
     If option 'p' is not used; missing variable chunk href will contain OPeNDAP_DMRpp_MISSING_DATA_ACCESS_URL.
     If option 'p' is selected; missing variable chunk href will contain the argument provided to that option
```

so we'll want to run this with -M, but not -u/-p switches. none of these switches are available to us from a configuration standpoint. Ideally we can leverage some flag information in the collection metadata of a cumulus task to enable/disable these items from a workflow.

**Comment by mgangl** [comment]
the outputs will need to be uploaded to the same s3 bucket, so we might have the *.nc, the *.nc.dmrpp, and optionally a *.nc.missing file for those taking advantage of it. 

Nga brought up a good point, the path of least resistance might be to always run with -M if we already don't allow access to the -u and -p flags.

**Comment by littleidiot40** [comment]
> always run with -M

Will this work for _all_ data? If so, this is a lot simpler. We just need to add it to the command line and make sure the task uploads the missing file too.

**Comment by amarouane-ABDELHAK** [comment]
Fixed, please refer to https://ghrcdaac.github.io/dmrpp-generator/#features-added-to-v200
