### ISSUE TITLE
Collect get_dmrpp output and place it in the log when get_dmrpp fails

### ISSUE THREAD

**Issue by ndp-opendap** [ghrcdaac/dmrpp-generator#14]
Currently this task detects and logs when the `get_dmrpp` application fails by checking it's exit status. That's good.
Unfortunately the output of `get_dmrpp` is lost and so the person running the task has absolutely no idea why it fails for a particular granule. That's bad.
Please collect the output of `get_dmrpp` and if the exit status is non-zero add the entire output to the log so the person running the task can better understand the reason for the failure(s).

**Comment by amarouane-ABDELHAK** [comment]
Fixed during the release v3.1.2
