### ISSUE TITLE
As a DMRPP integrator, i want to be able to run a set of test files agains the dmrpp-generator code so that i can validate outputs before integrating this into my cumulus workflows

### ISSUE THREAD

**Issue by mgangl** [ghrcdaac/dmrpp-generator#4]
The integration into cumulus looks straight forward, but for QA purposes, i'd like to generate and verify/validate the DMRPP files before running end to end in cumulus. By simply being able to point the DMRPP generator at a local file (or directory of files) and output dmrpp, i'd be able to validate those without cumulus integration and workflows. We'd also be able to quickly narrow down if an issue was because of our file + DRM, or with the cumulus integration portion.

**Comment by amarouane-ABDELHAK** [comment]
Thanks @mgangl  @ellett we need to convert this into a jira action to schedule it.

**Comment by amarouane-ABDELHAK** [comment]
Issue fixed now you can generate DMR++ files locally by running 
docker run --rm -it -v <path/to/nc/hdf/files>:/workstation ghrcdaac/dmrpp-generator
