### ISSUE TITLE
Fails when granuleId doesn't have an extension

### ISSUE THREAD

**Issue by lbaatz** [ghrcdaac/dmrpp-generator#9]
DMR++ generator currently works with hdf5 and netcdf4 files. Testing was simulated using a modified workflow with a netcdf file that was obtained by running the modis format converter on an hdf file. Browse and metadata files were also supplied.

It appears that DMR++ generator currently expects granuleId to include the file extension. It seems to expect the cmr.xml file to also have the file extension in the name. ex:
granuleId: MYD11A1.A2003185.h00v10.061.2019218233350.nc
metadata file: MYD11A1.A2003185.h00v10.061.2019218233350.nc.cmr.xml

We made a conscious decision to drop the extension from our granuleIds, so our names are:
granuleId: MYD11A1.A2003185.h00v10.061.2019218233350
metadata file: MYD11A1.A2003185.h00v10.061.2019218233350.cmr.xml

Using our names, the DMR++ generator renames the granuleId to have the extension, and it drops the metadata file from the output payload. It also drops the browse file from the output payload. In the next step, HyraxMetadataUpdates, it can't find the metadata file (because it's looking for *.nc.cmr.xml)

To facilitate workflow development, I modified the collection and cnm message to use a .nc granuleId and .nc.cmr.xml file.

Here's a sample collection definition from my testing:
{
"name": "MYD11A1",
"version": "061",
"dataType": "MYD11A1",
"process": "legacy",
"url_path": "MYD11A1.061",
"duplicateHandling": "replace",
"granuleId": "^MYD11A1.A\\d

{7}.h\\d{2}v\\d{2}.061.\\d{13}$",
"granuleIdExtraction": "(MYD11A1.A\\d{7}
.h\\d

{2}v\\d{2}
.061.\\d

{13})(
.nc)",
"reportToEms": false,
"sampleFileName": "MYD11A1.A2003185.h00v10.061.2019218233350.nc",
"files": [
{
"bucket": "protected",
"regex": "MYD11A1.A\\d{7}.h\\d{2}v\\d{2}.061.\\d{13}

.(nc|nc.dmrpp)$",
"sampleFileName": "MYD11A1.A2003185.h00v10.061.2019218233350.nc",
"type": "data"
},
{
"bucket": "protected",
"regex": "MYD11A1.A\\d

{7}.h\\d{2}v\\d{2}.061.\\d{13}
.nc.cmr.xml$",
"sampleFileName": "MYD11A1.A2003185.h00v10.061.2019218233350.nc.cmr.xml",
"type": "metadata"
},
{
"bucket": "public",
"regex": "BROWSE.MYD11A1.A\\d{7}
.h\\d

{2}v\\d{2}
.061.\\d

{13}
.
d.jpg$",
"sampleFileName": "BROWSE.MYD11A1.A2003185.h00v10.061.2019218233350.1.jpg",
"type": "browse"
}
],
"meta":

{ "glacier-bucket": "lpdaac-sandbox-cumulus-glacier", "backupFileTypes": [ ".nc", ".dmrpp", ".cmr.xml", ".jpg" ], "granuleRecoveryWorkflow": "DrRecoveryWorkflow", "requireCmrToken": true, "producerGranIdExt": ".hdf", "conversionScheme": "MODIS_HDF4_to_NetCDF4" }
}

Here’s a sample CNM message from my testing:

{
"product": {
"files": [
{ "checksumType": "MD5", "name": "MYD11A1.A2003185.h00v10.061.2019218233350.nc", "checksum": "8075972420e1a2067a257189e4eab286", "uri": "s3://lb-sndbx-internal/TEST/MYD11A1.061/MYD11A1.A2003185.h00v10.061.2019218233350.nc", "type": "data", "size": 2152221 }
,
{ "checksumType": "MD5", "name": "MYD11A1.A2003185.h00v10.061.2019218233350.nc.cmr.xml", "checksum": "6d69c9e20dce6eb73a00a36be7838ce5", "uri": "s3://lb-sndbx-internal/TEST/MYD11A1.061/MYD11A1.A2003185.h00v10.061.2019218233350.nc.cmr.xml", "type": "metadata", "size": 8936 }
,

{ "checksumType": "MD5", "name": "BROWSE.MYD11A1.A2003185.h00v10.061.2019218233350.1.jpg", "checksum": "69c3ffb2f55124c1b261fd342a9bd968", "uri": "s3://lb-sndbx-internal/TEST/MYD11A1.061/BROWSE.MYD11A1.A2003185.h00v10.061.2019218233350.1.jpg", "type": "browse", "size": 17660 }
],
"name": "MYD11A1.A2003185.h00v10.061.2019218233350.nc",
"dataVersion": "061"
},
"identifier ": "MYD11A1.A2003185.h00v10.061.2019218233350",
"collection": "MYD11A1",
"provider": "LPDAAC",
"version": "061"
}

With the .nc in the granuleId and metadata file names, it creates the .dmrpp file in the protected bucket, and updates the .nc.cmr.xml with an Opendap link. However, it’s still losing the input browse file in the DMR++ generation step.
To troubleshoot, I’ve tried naming the browse file:

BROWSE.MYD11A1.A2003185.h00v10.061.2019218233350.1.jpg
BROWSE.MYD11A1.A2003185.h00v10.061.2019218233350.1.nc.jpg
BROWSE.MYD11A1.A2003185.h00v10.061.2019218233350.nc.1.jpg
BROWSE.MYD11A1.A2003185.h00v10.061.2019218233350.nc.jpg (in addition, I also tried this one with putting browse in the protected bucket, instead of public bucket)

But in all cases the browse file is dropped from the output payload.

**Comment by amarouane-ABDELHAK** [comment]
Solved in v1.0.4 release
